name: Update README

on:
  push:
    paths:
      - '**/*.md'
      - '**/*.py'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important: this allows fetching all history for all branches and tags

      - name: Set up Python Env
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run Python Script for Update README.md
        run: python .github/scripts/update_readme.py

      - name: Commit changes
        run: |
          git config --global user.email "kimdobby@g.skku.edu"
          git config --global user.name "Dobby-Kim"
          git add README.md
          git commit -m "Auto Updated README.md with latest contributions" || echo "No changes to commit"

      - name: Pull changes
        run: git pull --rebase origin main

      - name: Push changes
        run: git push
